"""
Execute every query in sql/02_funnel_analysis.sql and write the output to
results/findings.md as rendered markdown tables.

Run:  python scripts/run_analysis.py
"""
import os
import re
import sqlite3

import pandas as pd

DB_PATH = os.path.join("data", "funnel.db")
SQL_PATH = os.path.join("sql", "02_funnel_analysis.sql")
OUT_PATH = os.path.join("results", "findings.md")


def split_queries(text):
    """Split the analysis file into (title, sql) pairs on the Qn. headers."""
    chunks = re.split(r"\n-{2} -{10,}\n(?=-- Q\d)", text)
    out = []
    for chunk in chunks:
        match = re.search(r"--\s*(Q\d+\..*)", chunk)
        if not match:
            continue
        sql = chunk[chunk.index(match.group(0)):]
        out.append((match.group(1).strip(), sql))
    return out


def main():
    if not os.path.exists(DB_PATH):
        raise SystemExit("data/funnel.db not found - run scripts/generate_data.py first")

    os.makedirs("results", exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    with open(SQL_PATH) as fh:
        queries = split_queries(fh.read())

    lines = [
        "# Funnel Diagnostic - Results",
        "",
        "Generated by `scripts/run_analysis.py`. Every table below is the raw output of the",
        "correspondingly numbered query in [`sql/02_funnel_analysis.sql`](../sql/02_funnel_analysis.sql).",
        "",
    ]

    for title, sql in queries:
        df = pd.read_sql_query(sql, conn)
        lines += [f"## {title}", "", df.to_markdown(index=False), ""]
        print(f"[ok] {title}  ({len(df)} rows)")

    conn.close()
    with open(OUT_PATH, "w") as fh:
        fh.write("\n".join(lines))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
